name: docker-build-push
description: Build and push Docker image.

inputs:
  module:
    required: true
    description: Subdirectory of the repository containing the Dockerfile.
  module_version:
    required: true
    description: Version of the module to build.
  registry:
    required: false
    default: ghcr.io
    description: Registry to push the image to.
  registry_username:
    required: false
    default: ${{ github.actor }}
    description: Username to login to the registry.
  registry_password:
    required: true
    description: Password to login to the registry.

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2

    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.module }}
        labels: |
          org.opencontainers.image.version=${{ inputs.module_version }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.title=${{ github.repository }}
        tags: |
          type=raw,value=${{ inputs.module_version }}
          type=pep440,pattern={{version}}
          type=pep440,pattern={{major}}.{{minor}}
          type=pep440,pattern={{major}}

    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.module }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: snok/container-retention-policy@v2
      with:
        image-names: "${{ github.repository }}/${{ inputs.module }}*"
        cut-off: one minute ago UTC
        keep-at-least: 3
        skip-tags: latest
        timestamp-to-use: updated_at
        account-type: personal
        token: ${{ inputs.registry_password }}
