name: docker-build-push-action
description: Build and push Docker image.

inputs:
  module:
    required: true
    description: Subdirectory of the repository containing the Dockerfile.
  module_version:
    required: true
    description: Version of the module to build.
  registry:
    required: false
    default: ghcr.io
    description: Registry to push the image to.
  registry_username:
    required: false
    default: ${{ github.actor }}
    description: Username to login to the registry.
  registry_password:
    required: true
    description: Password to login to the registry.

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.module }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.module }}:${{ inputs.module_version }}
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.module }}:latest
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: snok/container-retention-policy@v2
      with:
        image-names: "${{ inputs.module }}"
        untagged-only: false
        cut-off: one minute ago UTC
        keep-at-least: 3
        skip-tags: latest
        timestamp-to-use: updated_at
        account-type: personal
        token: ${{ inputs.registry_password }}
